const seed=[{id:1,name:"Minimal Ceramic Vase",cat:"Table Decor",price:699,old:999,icon:"🏺",desc:"Elegant ceramic accent for shelves and tables."},{id:2,name:"Abstract Wall Art",cat:"Wall Decor",price:899,old:1299,icon:"🖼️",desc:"Modern statement piece for your living room."},{id:3,name:"Warm Table Lamp",cat:"Lighting",price:1199,old:1699,icon:"🛋️",desc:"Soft ambient lighting with a premium look."},{id:4,name:"Meditating Buddha",cat:"Statues",price:799,old:1099,icon:"🪷",desc:"Peaceful décor for your home corner."},{id:5,name:"Decorative Tray",cat:"Table Decor",price:599,old:799,icon:"🍽️",desc:"A stylish tray for coffee tables and consoles."},{id:6,name:"Textured Wall Mirror",cat:"Wall Decor",price:1499,old:1999,icon:"🪞",desc:"A statement mirror with a refined finish."}];
if(!localStorage.products)localStorage.products=JSON.stringify(seed);
let cat="All",cart=JSON.parse(localStorage.cart||"[]");
const products=()=>JSON.parse(localStorage.products||"[]");
function setCat(c){cat=c;renderProducts()}
function renderProducts(){let q=(document.getElementById("search")?.value||"").toLowerCase();let arr=products().filter(p=>(cat==="All"||p.cat===cat)&&p.name.toLowerCase().includes(q));document.getElementById("products").innerHTML=arr.map(p=>`<article class="card"><div class="pic">${p.icon||"🏠"}</div><div class="cardInfo"><small>${p.cat}</small><h3>${p.name}</h3><span class="price">₹${p.price.toLocaleString("en-IN")}</span>${p.old?`<span class="old">₹${p.old.toLocaleString("en-IN")}</span>`:""}<button class="btn add" onclick="addCart(${p.id})">Add to cart</button></div></article>`).join("")||"<p>No products found.</p>"}
function addCart(id){let p=products().find(x=>x.id===id);cart.push(p);localStorage.cart=JSON.stringify(cart);updateCart();toggleCart()}
function toggleCart(){document.getElementById("cart").classList.toggle("open");updateCart()}
function updateCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartItems").innerHTML=cart.map((p,i)=>`<div class="cartRow"><div class="mini">${p.icon||"🏠"}</div><div><b>${p.name}</b><br>₹${p.price}<br><button onclick="removeCart(${i})">Remove</button></div></div>`).join("")||"<p>Your cart is empty.</p>";document.getElementById("total").textContent="₹"+cart.reduce((s,p)=>s+p.price,0).toLocaleString("en-IN")}
function removeCart(i){cart.splice(i,1);localStorage.cart=JSON.stringify(cart);updateCart()}
function checkout(){if(!cart.length)return alert("Add a product first.");let msg="Hello, I want to order:%0A"+cart.map(p=>`• ${p.name} - ₹${p.price}`).join("%0A");window.open("https://wa.me/?text="+msg,"_blank")}
renderProducts();updateCart();