const defaults=[
{id:1,name:'Buddha Water Fountain',category:'spiritual',price:'₹2,499',image:'assets/buddha-fountain.jpg',description:'A peaceful Buddha fountain designed to bring a calm focal point to your home.',specs:['Decorative Buddha fountain','Suitable for living room or meditation corner','Neutral stone finish']},
{id:2,name:'Meditating Buddha Decor',category:'spiritual',price:'₹1,499',image:'assets/buddha-statue.jpg',description:'Elegant meditation-inspired decor for living rooms, study spaces and pooja corners.',specs:['Meditating Buddha design','Neutral finish','Ideal for shelf or table styling']},
{id:3,name:'Luxury Buddha Accent',category:'decor',price:'₹1,899',image:'assets/buddha-statue.jpg',description:'A warm neutral statement piece for shelves, consoles and side tables.',specs:['Premium decorative look','Neutral home-friendly tone','Gift-friendly decor']},
{id:4,name:'Classic Home Accent',category:'decor',price:'₹999',image:'assets/buddha-fountain.jpg',description:'A versatile decor accent that complements modern and traditional interiors.',specs:['Home accent piece','Easy to style','Suitable for gifting']}
];
function products(){try{let x=JSON.parse(localStorage.getItem('gharSajawatProducts'));return Array.isArray(x)&&x.length?x:defaults}catch(e){return defaults}}
function render(cat='all'){let box=document.getElementById('products');if(!box)return;box.innerHTML=products().filter(p=>cat==='all'||p.category===cat).map(p=>`<article class="card"><a href="product.html?id=${encodeURIComponent(p.id)}"><div class="card-img"><img src="${p.image}" alt="${p.name}"></div><div class="card-body"><div class="card-cat">${p.category.toUpperCase()}</div><h3>${p.name}</h3><div class="price">${p.price}</div><span class="view">View details →</span></div></a></article>`).join('')}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.cat)});
document.getElementById('menu')?.addEventListener('click',()=>document.querySelector('.nav nav').classList.toggle('open'));render();
